config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :gradings
  end
  
  root 'patients#index'
end

app/models/grading.rb
class Grading < ActiveRecord::Base
	belongs_to :patient
	has_many :rights, dependent: :destroy
	accepts_nested_attributes_for :rights, reject_if: :all_blank, allow_destroy: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	Gender = %w(Male Female)
	has_many :gradings, dependent: :destroy
	validates :first_name, :surname, :address, :phone, presence: true
	def fullName
		self.first_name+' '+self.middle_name+' '+self.surname
	end
	def gradeCount
		self.gradings.size
	end
end

app/models/right.rb
class Right < ActiveRecord::Base
  belongs_to :grading
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gradings_controller.rb
class GradingsController < ApplicationController
  before_action :set_patient
  before_action :set_grading, only: [:show, :edit, :update, :destroy]
  before_action :set_right, only:[:show]

  def index
    @gradings = Grading.all
  end

  def show
  end

  def new
    @grading = @patient.gradings.build
  end

  def edit
  end

  def create
    @grading = @patient.gradings.build(grading_params)

    respond_to do |format|
      if @grading.save
        format.html { redirect_to [@patient, @grading], notice: 'Grading was successfully created.' }
        format.json { render :show, status: :created, location: @grading }
      else
        format.html { render :new }
        format.json { render json: @grading.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @grading.update(grading_params)
        format.html { redirect_to [@patient, @grading], notice: 'Grading was successfully updated.' }
        format.json { render :show, status: :ok, location: @grading }
      else
        format.html { render :edit }
        format.json { render json: @grading.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @grading.destroy
    respond_to do |format|
      format.html { redirect_to [@patient, @grading], notice: 'Grading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_right
      @right = @grading.rights.find(params[:id])
    end
    def set_grading
      @grading = @patient.gradings.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def grading_params
      params.require(:grading).permit(:right_eye_verdict, :left_eye_verdict, rights_attributes: [:id, :microaneurysms, :cotton_wool_spots, :flame_haemorrhages, :irma, :venous_beading, :vessels_elsewhere, :vessels_at_disc, :vitreous_haemorrhages, :retinal_detachment, :_destroy])
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :surname, :dob, :gender, :phone, :email, :address, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gradings_helper.rb
module GradingsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/gradings/_form.html.erb
<%= form_for([@patient, @grading], html: {multipart: true}) do |f| %>
  <% if @grading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grading.errors.count, "error") %> prohibited this grading from being saved:</h2>

      <ul>
      <% @grading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :right_eye_verdict %><br>
    <%= f.text_field :right_eye_verdict %>
  </div>
  <div id = 'right'>
    <%= f.fields_for :rights do |r| %>
    <%= render 'right_fields', f: r %>
    <% end %>
    <%= link_to_add_association 'Add Grading parameters', f, :rights %>
  </div>

  <div class="field">
    <%= f.label :left_eye_verdict %><br>
    <%= f.text_field :left_eye_verdict %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gradings/_right_fields.html.erb
<div class="nested-fields">
	<%= f.check_box :microaneurysms %>
	<%= f.label :microaneurysms %>
	<%= f.check_box :flame_haemorrhages %>
	<%= f.label :flame_haemorrhages %>
	<%= f.check_box :cotton_wool_spots %>
	<%= f.label :cotton_wool_spots %>
	<%= f.check_box :irma %>
	<%= f.label :irma %>
	<%= f.check_box :venous_beading %>
	<%= f.label :venous_beading %>
	<%= f.check_box :vessels_elsewhere %>
	<%= f.label :vessels_elsewhere %>
	<%= f.check_box :vessels_at_disc %>
	<%= f.label :vessels_at_disc %>
	<%= f.check_box :vitreous_haemorrhages %>
	<%= f.label :vitreous_haemorrhages %>
	<%= f.check_box :retinal_detachment %>
	<%= f.label :retinal_detachment %>
	<%= link_to_remove_association 'Remove', f %>
</div>

app/views/gradings/edit.html.erb
<h1>Editing Grading</h1>

<%= render 'form' %>

<%= link_to 'Show', [@patient, @grading] %> |
<%= link_to 'Back', patient_gradings_path %>

app/views/gradings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gradings for <%= @patient.fullName %></h1>
<p>Total: <%= @patient.gradeCount %></p>
<table>
  <thead>
    <tr>
      <th>Right eye verdict</th>
      <th>Left eye verdict</th>
      <th>Test Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gradings.each do |grading| %>
      <tr>
        <td><%= grading.right_eye_verdict %></td>
        <td><%= grading.left_eye_verdict %></td>
        <td><%= grading.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= link_to 'Show', patient_grading_path(@patient, grading) %></td>
        <td><%= link_to 'Edit', edit_patient_grading_path(@patient, grading) %></td>
        <td><%= link_to 'Destroy', patient_grading_path(@patient, grading), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grading', new_patient_grading_path(@patient) %>

app/views/gradings/new.html.erb
<h1>New Grading</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_gradings_path(@patient) %>

app/views/gradings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Right eye verdict:</strong>
  <%= @grading.right_eye_verdict %>
</p>
<p>
	<strong>Microaneurysms: </strong>
	<%= @right.microaneurysms %>
</p>
<p>
	<strong>Flame Haemorrhages: </strong>
	<%= @right.flame_haemorrhages %>
</p>
<p>
	<strong>Cotton Wool Spots: </strong>
	<%= @right.cotton_wool_spots %>
</p>
<p>
	<strong>IRMA: </strong>
	<%= @right.irma %>
</p>
<p>
	<strong>Venous beading: </strong>
	<%= @right.venous_beading %>
</p>
<p>
	<strong>Vessels elsewhere: </strong>
	<%= @right.vessels_elsewhere %>
</p>
<p>
	<strong>Vessels at disc: </strong>
	<%= @right.vessels_at_disc %>
</p>
<p>
	<strong>Vitreous Haemorrhages: </strong>
	<%= @right.vitreous_haemorrhages %>
</p>
<p>
	<strong>Retinal detachment: </strong>
	<%= @right.retinal_detachment %>
</p>
<p>
  <strong>Left eye verdict:</strong>
  <%= @grading.left_eye_verdict %>
</p>

<%= link_to 'Edit', [:edit, @patient, @grading] %> |
<%= link_to 'Back', patient_gradings_path(@patient) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edrs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, options_for_select(Patient::Gender, @patient.gender) %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Surname</th>
      <th>Dob</th>
      <th>Gender</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>State</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.middle_name %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.email %></td>
        <td><%= patient.address %></td>
        <td><%= patient.state %></td>
        <td><%= link_to 'Enter Grading', new_patient_grading_path(patient) %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @patient.middle_name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @patient.surname %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @patient.state %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>